wandb_version: 1

max_disp:
  desc: null
  value: 192
model:
  desc: null
  value: basic
data_path:
  desc: null
  value: data/SceneFlowData/
num_epochs:
  desc: null
  value: 10
restore_ckpt:
  desc: null
  value: null
save_path:
  desc: null
  value: checkpoints/2024-08-14_14-42-28
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 310
log_wandb:
  desc: null
  value: true
batch_size:
  desc: null
  value: 6
train_datasets:
  desc: null
  value:
  - sceneflow
lr:
  desc: null
  value: 0.001
image_size:
  desc: null
  value:
  - 256
  - 512
weight_decay:
  desc: null
  value: 1.0e-05
img_gamma:
  desc: null
  value: null
saturation_range:
  desc: null
  value: null
do_flip:
  desc: null
  value: false
spatial_scale:
  desc: null
  value:
  - 0
  - 0
noyjitter:
  desc: null
  value: false
cuda:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723660949
    t:
      1:
      - 1
      - 41
      - 55
      - 100
      2:
      - 1
      - 41
      - 55
      - 100
      3:
      - 16
      - 23
      4: 3.8.19
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
